title: Song Club Records
email: contact@songclubrecords.com
description: >- # this means to ignore newlines until "baseurl:"
  A new kind of record label
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://songclubrecords.com/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

#Social links
twitter_username: songclubrecords
instagram_username:  songclubrecords

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

paginate_path: "/news/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
